# Generated by Django 4.2.7 on 2023-11-21 19:11

from django.db import migrations, models
import student_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_locker_number_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=255, validators=[student_app.validators.validate_combination_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=255, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
